version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"    
    schedule:
      interval: "daily"  
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
