name: Show Commit Changes with Line Numbers

on:
  push:

jobs:
  show-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history required

      - name: Show changes for each commit with line numbers
        run: |
          # Save commits JSON safely
          echo '${{ toJson(github.event.commits) }}' > commits.json

          # Loop through each commit in this push
          for commit in $(jq -r '.[].id' commits.json); do
            echo "============================================"
            echo "🔍 Commit: $commit"
            echo "--------------------------------------------"
            git log -1 --pretty=format:"%h %s" $commit
            echo

            # For each file changed in this commit
            for file in $(git diff-tree --no-commit-id --name-only -r $commit); do
              stats=$(git show --stat --oneline $commit | grep "$file")

              # Extract all changed line numbers from diff hunks
              lines=$(git show --unified=0 $commit -- "$file" \
                | grep '^@@' \
                | sed -E 's/.*\+([0-9]+).*/\1/' \
                | paste -sd ", " -)

              if [ -n "$lines" ]; then
                echo " $stats    on line(s): $lines"
              else
                echo " $stats"
              fi
            done

            echo
            git show --stat --oneline $commit | tail -n 1
            echo "============================================"
          done
